/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/2EZ06LfaiAB
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Chivo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from "@/components/ui/card"
import Image from "next/image"
import dash from "@/public/images/dash.jpg"
import mobile from "@/public/images/mobile.jpg"
import web from "@/public/images/web.jpg"

export function ui() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="bg-primary text-primary-foreground px-4 md:px-6 py-4 flex items-center justify-around">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <MountainIcon className="h-6 w-6" />
          <span className="text-lg font-bold">Alumni Association</span>
        </Link>
        <nav className="hidden md:flex items-center gap-4">
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            Home
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            About
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            Events
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            Donate
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            Jobs
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            Contact
          </Link>
        </nav>
        <Button variant="outline" className="md:hidden">
          <MenuIcon className="h-6 w-6" />
          <span className="sr-only">Toggle menu</span>
        </Button>
      </header>
      <main className="flex-1">
        <section className="bg-primary text-primary-foreground py-12 md:py-24">
          <div className="ml-[300px] container px-4 md:px-6 grid gap-6 md:grid-cols-2 items-center">
            <div className="space-y-4">
              <h1 className="text-3xl md:text-5xl font-bold">Stay Connected with Your Alumni Association</h1>
              <p className="text-lg md:text-xl">
                Join our vibrant community, explore opportunities, and give back to your alma mater.
              </p>
              <div className="flex flex-col sm:flex-row gap-2">
                <Button variant="outline" className="bg-black">Join Now</Button>
                <Button>Donate</Button>
              </div>
            </div>
            <div>
            <Image
              src={dash}
              width={400}
              height={400}
              alt="Alumni Association"
              className="mx-auto"
              style={{ objectFit: "cover" , borderRadius: "1rem"}}
            />
            </div>
          </div>
        </section>
        <section className="ml-[200px] py-12 md:py-24">
          <div className="container px-4 md:px-6 grid gap-12">
            <div className="space-y-4 text-center">
              <h2 className="text-3xl md:text-4xl font-bold">Explore Our Key Features</h2>
              <p className="text-lg md:text-xl text-muted-foreground">
                Discover the powerful tools and resources available to our alumni community.
              </p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
              <Card className="p-6 bg-background shadow-sm hover:shadow-md transition-shadow">
                <CardHeader>
                  <CardTitle>Alumni Registration</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground">
                    Join our vibrant community and stay connected with your alma mater.
                  </p>
                </CardContent>
                <CardFooter>
                  <Link href="#" className="text-primary hover:underline" prefetch={false}>
                    Learn More
                  </Link>
                </CardFooter>
              </Card>
              <Card className="p-6 bg-background shadow-sm hover:shadow-md transition-shadow">
                <CardHeader>
                  <CardTitle>Donation Portal</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground">
                    Contribute to the growth and development of your college through secure donations.
                  </p>
                </CardContent>
                <CardFooter>
                  <Link href="#" className="text-primary hover:underline" prefetch={false}>
                    Learn More
                  </Link>
                </CardFooter>
              </Card>
              <Card className="p-6 bg-background shadow-sm hover:shadow-md transition-shadow">
                <CardHeader>
                  <CardTitle>Job Networking</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground">
                    Explore job opportunities, connect with fellow alumni, and advance your career.
                  </p>
                </CardContent>
                <CardFooter>
                  <Link href="#" className="text-primary hover:underline" prefetch={false}>
                    Learn More
                  </Link>
                </CardFooter>
              </Card>
              <Card className="p-6 bg-background shadow-sm hover:shadow-md transition-shadow">
                <CardHeader>
                  <CardTitle>Alumni Success Stories</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground">
                    Get inspired by the achievements and career trajectories of our distinguished alumni.
                  </p>
                </CardContent>
                <CardFooter>
                  <Link href="#" className="text-primary hover:underline" prefetch={false}>
                    Learn More
                  </Link>
                </CardFooter>
              </Card>
            </div>
          </div>
        </section>
        <section className=" bg-muted py-12 md:py-24">
          <div className="ml-[200px] container px-4 md:px-6 grid gap-12">
            <div className="space-y-4 text-center">
              <h2 className="text-3xl md:text-4xl font-bold">Connect with Us on the Go</h2>
              <p className="text-lg md:text-xl text-muted-foreground">
                Access our platform anytime, anywhere with our mobile app.
              </p>
            </div>
            <div className="ml-[200px] grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="flex flex-col items-start gap-4">
                <Image
                  src={mobile}
                  width="400"
                  height="400"
                  alt="Mobile App"
                  className="rounded-xl"
                  style={{ aspectRatio: "400/400", objectFit: "cover", borderRadius: "1rem", border: "1px solid pink" }}
                />
                <div className="space-y-2">
                  <h3 className="text-2xl font-bold">Mobile App</h3>
                  <p className="text-muted-foreground">
                    Stay connected with your alma mater on the go. Download our mobile app for iOS and Android.
                  </p>
                  <div className="flex gap-2">
                    <Link
                      href="#"
                      className="inline-flex items-center gap-2 text-primary hover:underline"
                      prefetch={false}
                    >
                      <AppleIcon className="h-6 w-6" />
                      <span>iOS App</span>
                    </Link>
                    <Link
                      href="#"
                      className="inline-flex items-center gap-2 text-primary hover:underline"
                      prefetch={false}
                    >
                      <SmartphoneIcon className="h-6 w-6" />
                      <span>Android App</span>
                    </Link>
                  </div>
                </div>
              </div>
              <div className="flex flex-col items-start gap-4">
                <Image
                  src={web}
                  width="400"
                  height="400"
                  alt="Web Platform"
                  className="rounded-xl"
                  style={{ aspectRatio: "400/400", objectFit: "cover", borderRadius: "1rem" }}  
                />
                <div className="space-y-2">
                  <h3 className="text-2xl font-bold">Web Platform</h3>
                  <p className="text-muted-foreground">
                    Explore our comprehensive web platform for a deeper engagement with the alumni community.
                  </p>
                  <Link href="#" className="text-primary hover:underline" prefetch={false}>
                    Visit the Web Platform
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-primary text-primary-foreground px-4 md:px-6 py-6 flex flex-col md:flex-row items-center justify-around">
        <div className="flex items-center gap-2">
          <MountainIcon className="h-6 w-6" />
          <span className="text-lg font-bold">Alumni Association</span>
        </div>
        <nav className="flex items-center gap-4 mt-4 md:mt-0">
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            Privacy Policy
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            Terms of Service
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            Contact Us
          </Link>
        </nav>
      </footer>
    </div>
  )
}

function AppleIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 20.94c1.5 0 2.75 1.06 4 1.06 3 0 6-8 6-12.22A4.91 4.91 0 0 0 17 5c-2.22 0-4 1.44-5 2-1-.56-2.78-2-5-2a4.9 4.9 0 0 0-5 4.78C2 14 5 22 8 22c1.25 0 2.5-1.06 4-1.06Z" />
      <path d="M10 2c1 .5 2 2 2 5" />
    </svg>
  )
}


function MenuIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function MountainIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function SmartphoneIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="14" height="20" x="5" y="2" rx="2" ry="2" />
      <path d="M12 18h.01" />
    </svg>
  )
}
